# Generated by Django 5.1.3 on 2024-12-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeon',
            name='imagen',
        ),
        migrations.AddField(
            model_name='campeon',
            name='region',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campeon',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campeon',
            name='rasgo_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campeon',
            name='rasgo_2',
            field=models.CharField(max_length=100),
        ),
    ]
